import { DatabaseSchema } from './types';

export const initialDatabaseData: DatabaseSchema = {
  admins: [
    {
      id: 'admin-1',
      email: 'admin@skillcert.org',
      name: 'System Administrator',
      password: 'admin123456', // In production, hashed with bcrypt
      role: 'SUPERADMIN',
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-01-01T00:00:00.000Z',
    },
  ],
  users: [
    {
      id: 'user-demo-1',
      name: 'Shardul Parihar',
      email: 'shardulparihar.work@gmail.com',
      phone: '+91 98765 43210',
      organization: 'Tech Academy Institute',
      createdAt: '2026-10-01T10:00:00.000Z',
      updatedAt: '2026-10-01T10:00:00.000Z',
    },
    {
      id: 'user-demo-2',
      name: 'Elena Rostova',
      email: 'elena.rostova@example.com',
      phone: '+1 555-0199',
      organization: 'Vanguard Engineering',
      createdAt: '2026-10-02T11:30:00.000Z',
      updatedAt: '2026-10-02T11:30:00.000Z',
    },
  ],
  tests: [
    {
      id: 'test-web-dev-1',
      title: 'Web Development Fundamentals Assessment',
      slug: 'web-development-fundamentals',
      description: 'Comprehensive industry examination evaluating modern HTML5, CSS3, modern JavaScript (ES6+), React core concepts, Git workflow, and web performance standards.',
      durationMinutes: 20,
      passingPercentage: 60,
      isPublished: true,
      certificateTitle: 'Certificate of Achievement',
      organizationName: 'SkillCert Global Institute',
      createdAt: '2026-01-15T09:00:00.000Z',
      updatedAt: '2026-10-01T09:00:00.000Z',
    },
  ],
  questions: [
    {
      id: 'q-1',
      testId: 'test-web-dev-1',
      text: 'Which HTML5 semantic element represents a self-contained composition in a document that is intended to be independently distributable or reusable?',
      type: 'MULTIPLE_CHOICE',
      marks: 1,
      order: 1,
      category: 'HTML',
      explanation: '<article> is intended for self-contained syndicatable content such as blog posts, news stories, or forum entries, whereas <section> represents a generic thematic grouping.',
      options: [],
    },
    {
      id: 'q-2',
      testId: 'test-web-dev-1',
      text: 'If an element has `box-sizing: border-box`, `width: 300px`, `padding: 20px`, and `border: 2px solid #000`, what is its final rendered total width on screen?',
      type: 'MULTIPLE_CHOICE',
      marks: 1,
      order: 2,
      category: 'CSS',
      explanation: 'Under border-box sizing, padding and border are contained within the declared 300px width. The rendered total width is exactly 300px.',
      options: [],
    },
    {
      id: 'q-3',
      testId: 'test-web-dev-1',
      text: 'In CSS Flexbox, which property controls alignment along the cross axis (perpendicular to the main axis)?',
      type: 'MULTIPLE_CHOICE',
      marks: 1,
      order: 3,
      category: 'CSS',
      explanation: '`justify-content` defines alignment along the main axis, while `align-items` defines how flex items align along the cross axis.',
      options: [],
    },
    {
      id: 'q-4',
      testId: 'test-web-dev-1',
      text: 'In the JavaScript Event Loop, which queue has priority and drains completely before the next macrotask is processed?',
      type: 'MULTIPLE_CHOICE',
      marks: 1,
      order: 4,
      category: 'JavaScript',
      explanation: 'Microtasks (Promises, queueMicrotask, MutationObserver) have higher priority than macrotasks (setTimeout, setInterval, I/O) and the microtask queue must be empty before the next macrotask executes.',
      options: [],
    },
    {
      id: 'q-5',
      testId: 'test-web-dev-1',
      text: 'What will be the output of `console.log(typeof null)` in JavaScript?',
      type: 'MULTIPLE_CHOICE',
      marks: 1,
      order: 5,
      category: 'JavaScript',
      explanation: 'Due to a historical bug in the first implementation of JavaScript where object type tags were represented by 0, `typeof null` returns "object".',
      options: [],
    },
    {
      id: 'q-6',
      testId: 'test-web-dev-1',
      text: 'True or False: Arrow functions in JavaScript retain lexical scoping for `this` and do not bind their own `this`, `arguments`, or `super`.',
      type: 'TRUE_FALSE',
      marks: 1,
      order: 6,
      category: 'JavaScript',
      explanation: 'True. Arrow functions do not have their own `this` context; they inherit `this` from the enclosing lexical scope.',
      options: [],
    },
    {
      id: 'q-7',
      testId: 'test-web-dev-1',
      text: 'In React, why should component state never be directly mutated (e.g., `user.name = "Alex"`) instead of using setter functions?',
      type: 'MULTIPLE_CHOICE',
      marks: 1,
      order: 7,
      category: 'React',
      explanation: 'Direct mutations do not change object references, causing React to miss state changes in shallow comparison, preventing component re-renders.',
      options: [],
    },
    {
      id: 'q-8',
      testId: 'test-web-dev-1',
      text: 'In React, when does the cleanup function returned by `useEffect` execute?',
      type: 'MULTIPLE_CHOICE',
      marks: 1,
      order: 8,
      category: 'React',
      explanation: 'The cleanup function executes before the component re-runs the effect on dependency change, as well as when the component unmounts.',
      options: [],
    },
    {
      id: 'q-9',
      testId: 'test-web-dev-1',
      text: 'True or False: In Git, `git rebase` creates a new merge commit preserving both branch histories verbatim, whereas `git merge` rewrites commit hashes linearly.',
      type: 'TRUE_FALSE',
      marks: 1,
      order: 9,
      category: 'Git',
      explanation: 'False. `git merge` preserves histories and creates a merge commit, while `git rebase` replays commits onto a new base, rewriting commit hashes.',
      options: [],
    },
    {
      id: 'q-10',
      testId: 'test-web-dev-1',
      text: 'What is the precise difference between HTTP status code 401 Unauthorized and 403 Forbidden?',
      type: 'MULTIPLE_CHOICE',
      marks: 1,
      order: 10,
      category: 'Web Fundamentals',
      explanation: '401 indicates missing or invalid authentication credentials (user identity unknown), while 403 means the identity is authenticated but lacks permission to access the resource.',
      options: [],
    },
  ],
  options: [
    // Q1 Options
    { id: 'opt-1-a', questionId: 'q-1', text: '<article>', isCorrect: true, order: 1 },
    { id: 'opt-1-b', questionId: 'q-1', text: '<section>', isCorrect: false, order: 2 },
    { id: 'opt-1-c', questionId: 'q-1', text: '<aside>', isCorrect: false, order: 3 },
    { id: 'opt-1-d', questionId: 'q-1', text: '<div>', isCorrect: false, order: 4 },

    // Q2 Options
    { id: 'opt-2-a', questionId: 'q-2', text: '300px', isCorrect: true, order: 1 },
    { id: 'opt-2-b', questionId: 'q-2', text: '344px', isCorrect: false, order: 2 },
    { id: 'opt-2-c', questionId: 'q-2', text: '320px', isCorrect: false, order: 3 },
    { id: 'opt-2-d', questionId: 'q-2', text: '256px', isCorrect: false, order: 4 },

    // Q3 Options
    { id: 'opt-3-a', questionId: 'q-3', text: 'justify-content', isCorrect: false, order: 1 },
    { id: 'opt-3-b', questionId: 'q-3', text: 'align-items', isCorrect: true, order: 2 },
    { id: 'opt-3-c', questionId: 'q-3', text: 'flex-direction', isCorrect: false, order: 3 },
    { id: 'opt-3-d', questionId: 'q-3', text: 'align-content', isCorrect: false, order: 4 },

    // Q4 Options
    { id: 'opt-4-a', questionId: 'q-4', text: 'Microtask Queue', isCorrect: true, order: 1 },
    { id: 'opt-4-b', questionId: 'q-4', text: 'Macrotask Queue (Task Queue)', isCorrect: false, order: 2 },
    { id: 'opt-4-c', questionId: 'q-4', text: 'Animation Frame Queue', isCorrect: false, order: 3 },
    { id: 'opt-4-d', questionId: 'q-4', text: 'I/O Polling Queue', isCorrect: false, order: 4 },

    // Q5 Options
    { id: 'opt-5-a', questionId: 'q-5', text: '"object"', isCorrect: true, order: 1 },
    { id: 'opt-5-b', questionId: 'q-5', text: '"null"', isCorrect: false, order: 2 },
    { id: 'opt-5-c', questionId: 'q-5', text: '"undefined"', isCorrect: false, order: 3 },
    { id: 'opt-5-d', questionId: 'q-5', text: '"boolean"', isCorrect: false, order: 4 },

    // Q6 Options (True / False)
    { id: 'opt-6-a', questionId: 'q-6', text: 'True', isCorrect: true, order: 1 },
    { id: 'opt-6-b', questionId: 'q-6', text: 'False', isCorrect: false, order: 2 },

    // Q7 Options
    { id: 'opt-7-a', questionId: 'q-7', text: 'React compares state by shallow reference equality; mutations do not trigger re-renders', isCorrect: true, order: 1 },
    { id: 'opt-7-b', questionId: 'q-7', text: 'Direct mutations crash the browser JavaScript garbage collector', isCorrect: false, order: 2 },
    { id: 'opt-7-c', questionId: 'q-7', text: 'Direct mutations convert state properties into strings', isCorrect: false, order: 3 },
    { id: 'opt-7-d', questionId: 'q-7', text: 'React immediately throws a runtime TypeError', isCorrect: false, order: 4 },

    // Q8 Options
    { id: 'opt-8-a', questionId: 'q-8', text: 'Before the next effect runs and during unmounting', isCorrect: true, order: 1 },
    { id: 'opt-8-b', questionId: 'q-8', text: 'Only when the browser window is closed', isCorrect: false, order: 2 },
    { id: 'opt-8-c', questionId: 'q-8', text: 'Immediately before the initial component render', isCorrect: false, order: 3 },
    { id: 'opt-8-d', questionId: 'q-8', text: 'Only once every 60 seconds', isCorrect: false, order: 4 },

    // Q9 Options (True / False)
    { id: 'opt-9-a', questionId: 'q-9', text: 'True', isCorrect: false, order: 1 },
    { id: 'opt-9-b', questionId: 'q-9', text: 'False', isCorrect: true, order: 2 },

    // Q10 Options
    { id: 'opt-10-a', questionId: 'q-10', text: '401 means unauthenticated (identity needed); 403 means authenticated but unauthorized (forbidden)', isCorrect: true, order: 1 },
    { id: 'opt-10-b', questionId: 'q-10', text: '401 is a client network timeout; 403 is an internal server database crash', isCorrect: false, order: 2 },
    { id: 'opt-10-c', questionId: 'q-10', text: '401 is for GET requests only; 403 is for POST and PUT requests', isCorrect: false, order: 3 },
    { id: 'opt-10-d', questionId: 'q-10', text: 'Both codes mean exactly the same and can be used interchangeably', isCorrect: false, order: 4 },
  ],
  attempts: [
    {
      id: 'attempt-demo-1',
      testId: 'test-web-dev-1',
      userId: 'user-demo-1',
      status: 'COMPLETED',
      startedAt: '2026-10-04T04:30:00.000Z',
      submittedAt: '2026-10-04T04:46:15.000Z',
      timeSpentSeconds: 975,
      tabSwitchCount: 0,
      totalQuestions: 10,
      correctAnswers: 9,
      incorrectAnswers: 1,
      unanswered: 0,
      score: 9,
      maxScore: 10,
      percentage: 90,
      isPassed: true,
      answers: [],
    },
    {
      id: 'attempt-demo-2',
      testId: 'test-web-dev-1',
      userId: 'user-demo-2',
      status: 'COMPLETED',
      startedAt: '2026-10-03T14:10:00.000Z',
      submittedAt: '2026-10-03T14:28:40.000Z',
      timeSpentSeconds: 1120,
      tabSwitchCount: 1,
      totalQuestions: 10,
      correctAnswers: 8,
      incorrectAnswers: 2,
      unanswered: 0,
      score: 8,
      maxScore: 10,
      percentage: 80,
      isPassed: true,
      answers: [],
    },
  ],
  answers: [],
  certificates: [
    {
      id: 'cert-db-1',
      certificateId: 'CERT-2026-8F42K9',
      attemptId: 'attempt-demo-1',
      userId: 'user-demo-1',
      testId: 'test-web-dev-1',
      participantName: 'Shardul Parihar',
      participantEmail: 'shardulparihar.work@gmail.com',
      testTitle: 'Web Development Fundamentals Assessment',
      score: 9,
      percentage: 90,
      issueDate: '2026-10-04T04:46:15.000Z',
      verificationUrl: '/verify/CERT-2026-8F42K9',
      emailSent: true,
      emailSentAt: '2026-10-04T04:46:20.000Z',
      createdAt: '2026-10-04T04:46:15.000Z',
    },
    {
      id: 'cert-db-2',
      certificateId: 'CERT-2026-9A77X2',
      attemptId: 'attempt-demo-2',
      userId: 'user-demo-2',
      testId: 'test-web-dev-1',
      participantName: 'Elena Rostova',
      participantEmail: 'elena.rostova@example.com',
      testTitle: 'Web Development Fundamentals Assessment',
      score: 8,
      percentage: 80,
      issueDate: '2026-10-03T14:28:40.000Z',
      verificationUrl: '/verify/CERT-2026-9A77X2',
      emailSent: true,
      emailSentAt: '2026-10-03T14:28:45.000Z',
      createdAt: '2026-10-03T14:28:40.000Z',
    },
  ],
  emailLogs: [
    {
      id: 'log-1',
      certificateId: 'CERT-2026-8F42K9',
      recipient: 'shardulparihar.work@gmail.com',
      emailType: 'CERTIFICATE_DELIVERY',
      status: 'DELIVERED',
      providerId: 'msg_resend_9921_demo',
      errorMessage: null,
      timestamp: '2026-10-04T04:46:20.000Z',
    },
    {
      id: 'log-2',
      certificateId: 'CERT-2026-9A77X2',
      recipient: 'elena.rostova@example.com',
      emailType: 'CERTIFICATE_DELIVERY',
      status: 'DELIVERED',
      providerId: 'msg_resend_8842_demo',
      errorMessage: null,
      timestamp: '2026-10-03T14:28:45.000Z',
    },
  ],
};
